# Site settings
title: Nigel Charleston - Programmer
email: ndcharle@umich.edu
description: >- # this means to ignore newlines until "baseurl:"
  This is Nigel Charleston's Portfolio
baseurl: "" # the subpath of your site, e.g. /blog
url: "localhost:4000" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  Nigel2016

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

exclude:
   - .sass-cache/
   - .jekyll-cache/
   - gemfiles/
   - Gemfile
   - Gemfile.lock
   - node_modules/
   - vendor/bundle/
   - vendor/cache/
   - vendor/gems/
   - vendor/ruby/
